FROM node:18-alpine
# Installing libvips-dev for sharp Compatability
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# WORKDIR /opt/
WORKDIR /app
COPY ./ ./

# ENV PATH /opt/node_modules/.bin:$PATH


# RUN npm install --registry=https://registry.npmmirror.com \
#   && npx nx run backend-strapi4:install

RUN npm install --registry=https://registry.npmmirror.com
RUN npx nx run backend-strapi4:install

COPY ./devDB/data.db ./apps/backend-strapi4/.tmp/data.db
COPY ./devDB/uploads/ ./apps/backend-strapi4/public/uploads/

EXPOSE 1337

CMD ["npx", "nx", "serve", "backend-strapi4"]
